[package]
name = "sampled"
version = "1.0.0"
authors = []

[addresses]
sampled_addr = "0xc8fda2536e05853bbb949dd40ccc086d722bb91008c7fd1757dc240e52f461e8"
std = "0x1"
aptos_framework = "0x1"
aptos_std = "0x1"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
