[package]
name = "sampled"
version = "1.0.0"
authors = []

[addresses]
sampled_addr = "0x3c3b81d1a1db763b1b28240b1ee07930dd89bacfdd79f7e9d13d120cd7f3b4ce"
std = "0x1"
aptos_framework = "0x1"
aptos_std = "0x1"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
