[package]
name = "sampled"
version = "1.0.0"
authors = []

[addresses]
sampled_addr = "0x462d050a0ff74fd8bb7afa8a70c3b63eedd7313cf5cfc1e47e285c7a3428a974"
std = "0x1"
aptos_framework = "0x1"
aptos_std = "0x1"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
